version: '3.5'
services:
  halley-api:
    container_name: halley-api
    build: .
    ports:
      - 3000:3000
    networks:
      - halley-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
  halley-redis-server:
    container_name: halley-redis-server
    image: 'redis:6.2-alpine'
    networks:
      - halley-network
    ports:
      - 6379:6379
networks:
  halley-network:
    driver: bridge
